### ISSUE TITLE
What do you think about page objects?

### ISSUE THREAD

**Issue by beleran** [vhumenskyi/qa_automation_test#7]

**Comment by vhumenskyi** [comment]
I believe it's related to some code line. Could you please provide more details?

**Comment by beleran** [comment]
This is related to the approach using page objects and the separation of concerns that they give.

**Comment by vhumenskyi** [comment]
The page object approach gives you possibility to reuse code and flexibility, also it allows you to spend less time for support if application was changes, so you need to update only page object classes and shows you exactly were problem is if you got error.
