### ISSUE TITLE
Cypress expects app to be on port 300, however docker runs it on 5000

### ISSUE THREAD

**Issue by beleran** [vhumenskyi/qa_automation_test#8]

**Comment by vhumenskyi** [comment]
But I rewrite it by this command - docker-compose run cypress ./node_modules/.bin/cypress run --config baseUrl=localhost:5000  as I understand it correctly

**Comment by beleran** [comment]
Yeah, but docker compose does not work. And local run does not have this rewrite in the manual

**Comment by vhumenskyi** [comment]
I'm not familiar with docker (be honest I use it for first time) and was able to run tests only locally, was not able to run it with docker and on Travis CI. I understand that you probably expect more, but for now I'm noob in docker. I change Dockerfile to expose 3000 but not sure it will work.
